const removeCsp = require('../lib/server/remove-csp');
const { describe, it } = require('mocha');
const assert = require('chai').assert;

describe('remove csp', () => {
    it('should remove meta tag from html string', () => {
        const html = '<meta property=og:title content="Роман Рождественский"><meta property=og:url content="https://rozhdestvenskiy.ru/"><meta name=yandex content=noindex><meta http-equiv=Content-Security-Policy content="child-src \'self\' data: blob: yabrowser: https://yandexadexchange.net https://*.yandexadexchange.net https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st https://*.yandex-team.ru; connect-src \'self\' https://ads.adfox.ru https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st https://*.yandex-team.ru; default-src \'none\'; font-src https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st; form-action https://yandex.ru https://*.yandex.ru https://*.yandex-team.ru https://*; img-src * \'self\' blob: data:; media-src * \'self\' data:; object-src \'self\' https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st; script-src \'self\' blob: \'nonce-9a575df0-58d7-11e8-8797-b3fb059df98c\' \'unsafe-inline\' \'unsafe-eval\' https://ads.adfox.ru https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st https://*.yandex-team.ru; style-src \'self\' \'unsafe-inline\' https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st; worker-src blob: https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st https://*.yandex-team.ru; frame-src \'self\' data: blob: yabrowser: https://yandexadexchange.net https://*.yandexadexchange.net https://yandex.ru https://*.yandex.ru https://yastatic.net https://*.yastatic.net https://yandex.net https://*.yandex.net https://yandex.st https://*.yandex-team.ru; "><style data-name=default>';
        const htmlWithoutCSP = '<meta property=og:title content="Роман Рождественский"><meta property=og:url content="https://rozhdestvenskiy.ru/"><meta name=yandex content=noindex><style data-name=default>';
        assert.equal(removeCsp(html), htmlWithoutCSP);
    });
});