- https://news.yandex.ru
- https://news.yandex.ua
- https://news.yandex.kz
- https://news.yandex.by
- https://news.yandex.fr
- https://m.news.yandex.ru
- https://m.news.yandex.ua
- https://m.news.yandex.kz
- https://m.news.yandex.by
- https://m.news.yandex.fr
